version: "3.7"
services:
  dns:
    image: nginx
    restart: unless-stopped
    networks:
      mdnp_net:
        ipv4_address: 192.168.2.249

networks:
    mdnp_net:
        name: "mynet"
        external: true